strategy:
  matrix:
    # Ubuntu 18.04 (testing)
    Ubuntu-18-test:
      imageName: 'ubuntu-18.04'
      pythonVer: '3.7'
      cmakeConfigArgs: ''
      cmakeBuildArgs: ''
      jobType: 'testing'
    # Ubuntu 16.04 (testing)
    Ubuntu-16-test:
      imageName: 'ubuntu-16.04'
      pythonVer: '3.5'
      cmakeConfigArgs: ''
      cmakeBuildArgs: ''
      jobType: 'testing'
#    # Ubuntu latest (coverage)
#    Ubuntu-coverage:
#      imageName: 'ubuntu-16.04'
#      cmakeConfigArgs: ''
#      cmakeBuildArgs: ''
#      jobType: 'coverage'
    # macOS Mojave (testing)
    macOS-14-test:
      imageName: 'macOS-10.14'
      pythonVer: '3.7'
      cmakeConfigArgs: ''
      cmakeBuildArgs: ''
      jobType: 'testing'
    # macOS High Sierra (testing)
    macOS-13-test:
      imageName: 'macOS-10.13'
      pythonVer: '3.5'
      cmakeConfigArgs: ''
      cmakeBuildArgs: ''
      jobType: 'testing'
    # Windows (testing)
    Windows-unit:
      imageName: 'windows-2019'
      pythonVer: '3.7'
      cmakeConfigArgs: ''
      cmakeBuildArgs: ''
      jobType: 'testing'

trigger:
  - master

pool:
  vmImage: $(imageName)

variables:
  aptDeps: 'libboost-all-dev lcov'
  brewDeps: 'boost libomp'
  vcpkgDeps: 'boost-algorithm boost-align boost-iostreams boost-program-options boost-math zlib'

steps:

  - checkout: self
    submodules: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVer)'
      architecture: 'x64'

  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '.. $(cmakeConfigArgs)'
    displayName: 'CMake'

  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '--build . $(cmakeBuildArgs)'
    displayName: 'Build'

  - script: ctest -V
    displayName: 'Unit tests'
    condition: in(variables['jobType'], 'testing', 'coverage')
    workingDirectory: 'build'

  - script: |
      lcov --directory . --capture --output-file coverage.info
      lcov --remove coverage.info '/usr/*' '*/TESTS/*' --output-file coverage.info
      lcov --list coverage.info
      bash <(curl https://codecov.io/bash) -f coverage.info -t 3ad5d7a8-138a-4041-acdf-bbf26f2cc491
    displayName: 'Upload coverage'
    workingDirectory: 'build'
    condition: eq(variables['jobType'], 'coverage')
